/* ========== CLASS IX ENGLISH INTERACTIVE READER ========== */
/* FULL texts - every line covered + sentence Bengali + Voice */

const lessons = {
  "north-ship": {
    title: "The North Ship",
    author: "Philip Larkin",
    initials: "PL",
    bio: "Philip Arthur Larkin (1922–1985) was a renowned English poet and novelist. His first book of poetry was The North Ship, followed by two novels, Jill and A Girl in Winter. He came to prominence in 1955 with the publication of his second collection of poems, The Less Deceived, followed by The Whitsun Weddings and High Windows. He was offered the position of Poet Laureate in 1984 but he declined it.",
    critical: "‘The North Ship’ uses three ships as symbols of life choices. The first two ships represent safer, conventional paths (wealth and captivity). The third ship that sails north into an unforgiving sea stands for the difficult but authentic journey of the individual or artist. Larkin’s tone of quiet determination and melancholy is already clear in this early poem.",
    sentences: [
      { en: "I saw three ships go sailing by,", bn: "আমি তিনটি জাহাজকে পাল তুলে যেতে দেখেছিলাম,", type: "poem" },
      { en: "Over the sea, the lifting sea,", bn: "উত্তোলিত সমুদ্রের উপর দিয়ে,", type: "poem" },
      { en: "And the wind rose in the morning sky,", bn: "এবং সকালের আকাশে বাতাস উঠেছিল,", type: "poem" },
      { en: "And one was rigged for a long journey.", bn: "এবং একটি দীর্ঘ যাত্রার জন্য সজ্জিত ছিল।", type: "poem" },
      { en: "The first ship turned towards the west,", bn: "প্রথম জাহাজটি পশ্চিম দিকে ঘুরে গেল,", type: "poem" },
      { en: "Over the sea, the running sea,", bn: "প্রবাহিত সমুদ্রের উপর দিয়ে,", type: "poem" },
      { en: "And by the wind was all possessed", bn: "এবং বাতাস তাকে পুরোপুরি অধিকার করে নিল", type: "poem" },
      { en: "And carried to a rich country.", bn: "এবং তাকে একটি সমৃদ্ধ দেশে নিয়ে গেল।", type: "poem" },
      { en: "The second turned towards the east,", bn: "দ্বিতীয়টি পূর্ব দিকে ঘুরে গেল,", type: "poem" },
      { en: "Over the sea, the quaking sea,", bn: "কম্পমান সমুদ্রের উপর দিয়ে,", type: "poem" },
      { en: "And the wind hunted it like a beast", bn: "এবং বাতাস তাকে শিকারের মতো তাড়া করল", type: "poem" },
      { en: "To anchor in captivity.", bn: "বন্দিত্বে নোঙর ফেলার জন্য।", type: "poem" },
      { en: "The third ship drove toward the north,", bn: "তৃতীয় জাহাজটি উত্তর দিকে চালিত হল,", type: "poem" },
      { en: "Over the sea, the darkening sea,", bn: "অন্ধকার হয়ে আসা সমুদ্রের উপর দিয়ে,", type: "poem" },
      { en: "But no breath of wind came forth,", bn: "কিন্তু কোনো বাতাসের শ্বাস এল না,", type: "poem" },
      { en: "And the decks shone frostily.", bn: "এবং ডেকগুলি হিমশীতলভাবে ঝলমল করছিল।", type: "poem" },
      { en: "The northern sky rose high and black", bn: "উত্তরের আকাশ উঁচু ও কালো হয়ে উঠল", type: "poem" },
      { en: "Over the proud unfruitful sea,", bn: "গর্বিত নিষ্ফল সমুদ্রের উপর,", type: "poem" },
      { en: "East and west the ships came back", bn: "পূর্ব ও পশ্চিম থেকে জাহাজগুলি ফিরে এল", type: "poem" },
      { en: "Happily or unhappily.", bn: "সুখে বা দুঃখে।", type: "poem" },
      { en: "But the third went wide and far", bn: "কিন্তু তৃতীয়টি দূরে ও প্রশস্ত পথে চলে গেল", type: "poem" },
      { en: "Into an unforgiving sea", bn: "একটি নির্দয় সমুদ্রে", type: "poem" },
      { en: "Under a fire-spilling star,", bn: "অগ্নি-ঝরা তারার নিচে,", type: "poem" },
      { en: "And it was rigged for a long journey.", bn: "এবং এটি দীর্ঘ যাত্রার জন্য সজ্জিত ছিল।", type: "poem" }
    ],
    words: {
      rigged: { en: "a boat or a ship equipped for a long journey", bn: "দীর্ঘ যাত্রার জন্য সজ্জিত নৌকা বা জাহাজ" },
      quaking: { en: "stirring", bn: "কম্পমান" },
      captivity: { en: "imprisonment", bn: "বন্দিত্ব" }
    }
  },

  "bananas": {
    title: "The Price of Bananas",
    author: "Mulk Raj Anand",
    initials: "MRA",
    bio: "Mulk Raj Anand (1905–2004) was a prolific writer who earned great admiration for his short stories and novels like ‘Coolie’, ‘Untouchable’, ‘The Village’, etc. where he depicted the lives of the poorer castes in traditional Indian society.",
    critical: "Anand uses humour and irony to expose class inequality. The monkey episode is comic, but the real focus is the contrast between the generous poor fruit-vendor and the mean rich Sethji. The story criticises the callousness of the privileged class who take help but refuse to pay even a small price for it.",
    sentences: [
      { en: "I was on my way from Faizabad railway station to Lucknow.", bn: "আমি ফৈজাবাদ রেলওয়ে স্টেশন থেকে লখনউ যাচ্ছিলাম।" },
      { en: "I had arrived at the station half an hour in advance of the time for the train’s departure.", bn: "ট্রেনের ছাড়ার সময়ের আধ ঘণ্টা আগে স্টেশনে পৌঁছেছিলাম।" },
      { en: "I sat on a bench watching the monkeys frolicking on the trees and on the open platform.", bn: "আমি একটি বেঞ্চে বসে গাছের উপর এবং খোলা প্ল্যাটফর্মে বানরদের খেলা দেখছিলাম।" },
      { en: "The monkeys descended now and then to collect half-sucked mango stones and the remainders of food from the platform.", bn: "বানররা মাঝে মাঝে নেমে এসে অর্ধেক চুষে খাওয়া আমের আঁটি ও খাবারের অবশিষ্টাংশ সংগ্রহ করছিল।" },
      { en: "The younger monkeys sat on the boughs of neem and tamarind trees, ready to jump after any food that may be visible.", bn: "ছোট বানররা নিম ও তেঁতুল গাছের ডালে বসেছিল, যেকোনো খাবার দেখলে লাফানোর জন্য প্রস্তুত।" },
      { en: "Just then the train was announced by the ringing of the station bell.", bn: "ঠিক তখন স্টেশনের ঘণ্টা বাজিয়ে ট্রেন ঘোষণা করা হল।" },
      { en: "I concentrated on securing a seat for myself in the train.", bn: "আমি ট্রেনে নিজের জন্য একটি আসন নিশ্চিত করতে মনোযোগ দিলাম।" },
      { en: "I got a window seat overlooking the platform.", bn: "আমি প্ল্যাটফর্মের দিকে তাকিয়ে একটি জানালার আসন পেলাম।" },
      { en: "Some other passengers joined me in the compartment.", bn: "কিছু অন্য যাত্রী আমার সঙ্গে কামরায় উঠল।" },
      { en: "We were all sweating from the rising heat of the summer.", bn: "আমরা সবাই গ্রীষ্মের বাড়তে থাকা গরমে ঘামছিলাম।" },
      { en: "Several passengers were busy filling up their small earthen pitchers from a water pump.", bn: "কয়েকজন যাত্রী একটি জলের পাম্প থেকে তাদের ছোট মাটির কলসি ভরতে ব্যস্ত ছিল।" },
      { en: "I was struck by the genius of a monkey in snatching away the loin cloth of a pious person who was taking a bath under the pump.", bn: "একজন ধার্মিক ব্যক্তি পাম্পের নিচে স্নান করছিলেন, তার লুঙ্গি কেড়ে নেওয়া একটি বানরের বুদ্ধিমত্তায় আমি অবাক হয়েছিলাম।" },
      { en: "A great deal of general amusement was caused by this incident.", bn: "এই ঘটনায় সবাই খুব মজা পেয়েছিল।" },
      { en: "The bather then requested the monkey to return his loin cloth.", bn: "স্নানকারী তখন বানরকে তার লুঙ্গি ফিরিয়ে দিতে অনুরোধ করলেন।" },
      { en: "The monkey was generous and threw it down from the neem tree at the man’s feet.", bn: "বানর উদার ছিল এবং নিম গাছ থেকে লুঙ্গিটি মানুষটির পায়ের কাছে ফেলে দিল।" },
      { en: "While all this was going on, I noticed a gentleman come up to our compartment.", bn: "এইসব ঘটনার মধ্যে আমি দেখলাম একজন ভদ্রলোক আমাদের কামরায় এসেছেন।" },
      { en: "He looked like a businessman.", bn: "তিনি একজন ব্যবসায়ীর মতো দেখাচ্ছিলেন।" },
      { en: "He was dressed in a white muslin dhoti, a delicate tunic and an embroidered cap on his head.", bn: "তিনি সাদা মসলিন ধুতি, সূক্ষ্ম পাঞ্জাবি এবং মাথায় সূচিকর্ম করা টুপি পরেছিলেন।" },
      { en: "A porter was carrying his luggage which included a big steel trunk, several small baskets and a brass jug.", bn: "একজন কুলি তার মালপত্র বহন করছিল, যার মধ্যে একটি বড় স্টিলের ট্রাঙ্ক, কয়েকটি ছোট ঝুড়ি এবং একটি পিতলের জগ ছিল।" },
      { en: "The man was shouting at the porter to hurry up with the luggage.", bn: "লোকটি কুলিকে মালপত্র নিয়ে তাড়াতাড়ি করতে বলছিল।" },
      { en: "Suddenly a monkey leapt down from the top of our compartment and snatched away the fine embroidered cap of the businessman.", bn: "হঠাৎ একটি বানর আমাদের কামরার উপর থেকে লাফিয়ে নেমে ব্যবসায়ীর সূক্ষ্ম সূচিকর্ম করা টুপি কেড়ে নিল।" },
      { en: "The monkey then climbed up the neem tree.", bn: "বানরটি তখন নিম গাছে উঠে গেল।" },
      { en: "“What have you done, monkey!” The businessman shouted, in utter confusion.", bn: "“তুই কী করলি, বানর!” ব্যবসায়ী সম্পূর্ণ বিভ্রান্ত হয়ে চিৎকার করল।" },
      { en: "His round and smug face was covered with perspiration.", bn: "তার গোল ও আত্মতুষ্ট মুখ ঘামে ঢাকা পড়ে গিয়েছিল।" },
      { en: "He ran towards the tree over the pump and stood threatening the monkey.", bn: "সে পাম্পের উপর দিয়ে গাছের দিকে দৌড়ে গিয়ে বানরকে ভয় দেখাতে লাগল।" },
      { en: "However, the more he shouted at the monkey, the remoter the monkey became.", bn: "তবে সে যতই বানরকে চিৎকার করল, বানর ততই দূরে সরে গেল।" },
      { en: "It was the same monkey that had snatched the bather’s loin cloth.", bn: "এটি সেই একই বানর যে স্নানকারীর লুঙ্গি কেড়ে নিয়েছিল।" },
      { en: "The people on the platform were much amused by the plight of the businessman.", bn: "প্ল্যাটফর্মের লোকেরা ব্যবসায়ীর দুর্দশা দেখে খুবই মজা পেল।" },
      { en: "He looked with a piteous and hopeless expression on his face.", bn: "তার মুখে করুণ ও নিরাশার ভাব ফুটে উঠেছিল।" },
      { en: "Meanwhile, a fruit vendor had come forward, pushing his little cart.", bn: "ইতিমধ্যে একজন ফল বিক্রেতা তার ছোট গাড়ি ঠেলে এগিয়ে এল।" },
      { en: "He told the Sethji that he would rescue the cap.", bn: "সে সেঠজিকে বলল যে সে টুপি উদ্ধার করবে।" },
      { en: "The businessman seemed slightly relieved.", bn: "ব্যবসায়ী কিছুটা স্বস্তি পেল।" },
      { en: "The vendor went ahead, dangling a couple of bananas at the monkey with his right hand.", bn: "বিক্রেতা এগিয়ে গিয়ে ডান হাতে কয়েকটি কলা বানরের সামনে দুলাতে লাগল।" },
      { en: "He stretched out his left hand for the cap.", bn: "সে বাম হাত বাড়িয়ে টুপির জন্য অপেক্ষা করল।" },
      { en: "The monkey seemed to hesitate.", bn: "বানরটি ইতস্তত করছিল।" },
      { en: "“Ao, ao, come down,” the vendor coaxed the monkey.", bn: "“আও, আও, নেমে আয়,” বিক্রেতা বানরকে প্ররোচিত করল।" },
      { en: "He lifted the bananas higher up.", bn: "সে কলাগুলো আরও উপরে তুলল।" },
      { en: "The monkey responded by climbing down cautiously to a branch near the vendor.", bn: "বানর সাবধানে নেমে এসে বিক্রেতার কাছের একটি ডালে এল।" },
      { en: "Looking this side and that, accepted the bargain.", bn: "এদিক-ওদিক তাকিয়ে সে চুক্তি মেনে নিল।" },
      { en: "It took over the bananas with his right hand and released the embroidered cap, slightly crumpled, with its left hand.", bn: "সে ডান হাতে কলা নিল এবং বাম হাতে সামান্য কুঁচকানো সূচিকর্ম করা টুপি ছেড়ে দিল।" },
      { en: "The spectators shouted in praise.", bn: "দর্শকরা প্রশংসায় চিৎকার করল।" },
      { en: "The fruit vendor came and humbly offered the Sethji his cap.", bn: "ফল বিক্রেতা এসে নম্রভাবে সেঠজিকে তার টুপি দিয়ে বলল।" },
      { en: "“They are hungry,” he said, “so they disturb the passengers.”", bn: "“ওরা ক্ষুধার্ত,” সে বলল, “তাই যাত্রীদের বিরক্ত করে।”" },
      { en: "“Acha,” said the Sethji, and turned to go into the compartment.", bn: "“আচ্ছা,” সেঠজি বলল এবং কামরায় ঢোকার জন্য ঘুরল।" },
      { en: "The vendor said, “Sethji, please give me two annas for the bananas which I had to offer to the monkey.”", bn: "বিক্রেতা বলল, “সেঠজি, দয়া করে যে কলাগুলো বানরকে দিতে হয়েছিল তার জন্য দুই আনা দিন।”" },
      { en: "“Two annas! What impudence!” Sethji shouted each word in disgust at the grimy fruit vendor.", bn: "“দুই আনা! কী ধৃষ্টতা!” সেঠজি নোংরা ফল বিক্রেতার দিকে ঘৃণায় প্রতিটি শব্দ চিৎকার করে বলল।" },
      { en: "“Please give him the money, Sethji,” the rest of the compartment said.", bn: "“দয়া করে তাকে টাকা দিন, সেঠজি,” কামরার বাকিরা বলল।" },
      { en: "“Acha, here are four annas for you, porter, and an anna for you, fruit vendor!” Sethji said.", bn: "“আচ্ছা, তোমাকে চার আনা, কুলি, আর তোমাকে এক আনা, ফল বিক্রেতা!” সেঠজি বলল।" },
      { en: "“But I carried two big pieces of luggage,” the porter wailed.", bn: "“কিন্তু আমি দুটো বড় মাল বহন করেছি,” কুলি কেঁদে বলল।" },
      { en: "“Go! Go! Crook!” Sethji thundered at the protesting porter.", bn: "“যা! যা! প্রতারক!” সেঠজি প্রতিবাদকারী কুলির দিকে গর্জন করল।" },
      { en: "The porter left.", bn: "কুলি চলে গেল।" },
      { en: "The fruit vendor persisted, “Sethji, be just, I saved your honourable cap...”", bn: "ফল বিক্রেতা জিদ ধরল, “সেঠজি, ন্যায় করুন, আমি আপনার সম্মানিত টুপি বাঁচিয়েছি...”" },
      { en: "The businessman threw an anna towards him on the platform.", bn: "ব্যবসায়ী প্ল্যাটফর্মে তার দিকে এক আনা ছুড়ে দিল।" },
      { en: "The guard’s whistle blew.", bn: "গার্ডের হুইসেল বাজল।" },
      { en: "The train was about to depart.", bn: "ট্রেন ছাড়তে চলেছে।" },
      { en: "The vendor looked in through the compartment window.", bn: "বিক্রেতা কামরার জানালার ভিতর দিয়ে তাকাল।" },
      { en: "“Sethji, do not rob the poor!”", bn: "“সেঠজি, গরিবকে লুটবেন না!”" },
      { en: "“Ja, ja! Take rest,” the Sethji scowled at him.", bn: "“যা, যা! বিশ্রাম নাও,” সেঠজি রাগে তাকিয়ে বলল।" },
      { en: "The train had begun to move.", bn: "ট্রেন নড়া শুরু করেছিল।" },
      { en: "The fruit vendor first ran along with it, then got on to the footstep and clung to the window, pleading.", bn: "ফল বিক্রেতা প্রথমে ট্রেনের সঙ্গে দৌড়াল, তারপর ফুটস্টেপে উঠে জানালায় ধরে অনুরোধ করতে লাগল।" },
      { en: "But Sethji had turned his head away.", bn: "কিন্তু সেঠজি মুখ ফিরিয়ে নিয়েছিল।" },
      { en: "He was looking out of the window at the goods train on the other side.", bn: "সে অন্য দিকের মালবাহী ট্রেনের দিকে জানালা দিয়ে তাকিয়ে ছিল।" },
      { en: "The train had passed the whole length of the platform and the frustrated vendor finally dropped off.", bn: "ট্রেন পুরো প্ল্যাটফর্ম পার হয়ে গেল এবং হতাশ বিক্রেতা অবশেষে নেমে পড়ল।" },
      { en: "Sethji turned round to all of us and began to justify himself,", bn: "সেঠজি আমাদের সবার দিকে ঘুরে নিজেকে ন্যায়সঙ্গত প্রমাণ করতে শুরু করল," },
      { en: "“If he did not want to help me to get my cap back, he should not have offered the monkey the bananas. I did not ask him to help.”", bn: "“যদি সে আমার টুপি ফেরত পেতে সাহায্য করতে না চাইত, তাহলে বানরকে কলা দিত না। আমি তাকে সাহায্য করতে বলিনি।”" },
      { en: "I felt that all the other passengers had sympathy for the poor vendor.", bn: "আমার মনে হল অন্য সব যাত্রীর গরিব বিক্রেতার প্রতি সহানুভূতি ছিল।" },
      { en: "The whole amusing episode had ended in a bitter sense of grievance against the rich businessman who had been so hard to the generous-hearted fruit vendor.", bn: "পুরো মজার ঘটনাটি ধনী ব্যবসায়ীর বিরুদ্ধে তিক্ত অভিযোগের অনুভূতিতে শেষ হয়েছিল, যে উদার মনের ফল বিক্রেতার প্রতি এত কঠোর হয়েছিল।" },
      { en: "I drew a cartoon of Sethji and showed my drawing to all the other passengers except him.", bn: "আমি সেঠজির একটি কার্টুন এঁকে তাকে বাদ দিয়ে অন্য সব যাত্রীকে দেখালাম।" },
      { en: "Everyone laughed.", bn: "সবাই হাসল।" },
      { en: "The more we laughed, Sethji became the more uncomfortable.", bn: "আমরা যত হাসলাম, সেঠজি ততই অস্বস্তিতে পড়ল।" }
    ],
    words: {
      frolicking: { en: "playing around in a lively, happy way", bn: "প্রাণবন্ত ও সুখীভাবে খেলা করা" },
      perspiration: { en: "sweat", bn: "ঘাম" },
      coaxed: { en: "persuaded somebody earnestly", bn: "আন্তরিকভাবে প্ররোচিত করা" },
      crumpled: { en: "crushed", bn: "কুঁচকানো" },
      anna: { en: "an old form of Indian currency (16 annas used to make a rupee)", bn: "পুরনো ভারতীয় মুদ্রা (১৬ আনায় ১ টাকা)" },
      impudence: { en: "rudeness", bn: "ধৃষ্টতা" },
      grimy: { en: "covered with dirt", bn: "ময়লায় ঢাকা" },
      crook: { en: "a dishonest person", bn: "অসৎ ব্যক্তি" },
      scowled: { en: "looked at somebody angrily", bn: "রাগে তাকানো" }
    }
  },
    "sailor": {
    title: "A Shipwrecked Sailor",
    author: "Daniel Defoe",
    initials: "DD",
    bio: "Daniel Defoe (1660–1731) was an English writer and journalist. He is most famous for his novel Robinson Crusoe. A prolific and versatile writer, Defoe is also known for pamphlets and journals on various topics.",
    critical: "This extract shows human resilience and self-reliance. Crusoe’s methodical work — building a fort, keeping a calendar, growing food — highlights the triumph of reason and hard work over despair. The island becomes a symbol of civilisation created by human effort.",
    sentences: [
      { en: "On September 30, 1659, I, miserable Robinson Crusoe, being shipwrecked during a violent storm, came on shore on this dismal island.", bn: "৩০ সেপ্টেম্বর ১৬৫৯-এ, আমি দুঃখী রবিনসন ক্রুশো, ভয়ংকর ঝড়ে জাহাজডুবি হয়ে এই বিষণ্ণ দ্বীপে এসে পৌঁছলাম।" },
      { en: "I call it the Island of Despair.", bn: "আমি একে নিরাশার দ্বীপ বলি।" },
      { en: "I was almost dead and the rest of my ship’s company was drowned.", bn: "আমি প্রায় মৃত এবং আমার জাহাজের বাকি সবাই ডুবে গিয়েছিল।" },
      { en: "I had neither food, house nor clothes.", bn: "আমার না ছিল খাবার, না বাড়ি, না কাপড়।" },
      { en: "I feared I would be devoured by wild beasts.", bn: "আমি ভয় পেয়েছিলাম যে বন্য পশুরা আমাকে খেয়ে ফেলবে।" },
      { en: "When night came, I slept in a tree for fear of wild creatures.", bn: "রাত হলে বন্য প্রাণীর ভয়ে আমি গাছে ঘুমিয়েছিলাম।" },
      { en: "It rained all night.", bn: "সারা রাত বৃষ্টি হয়েছিল।" },
      { en: "The rain continued through the next day with gusts of wind.", bn: "পরের দিনও বৃষ্টি ও ঝোড়ো হাওয়া চলতে থাকল।" },
      { en: "Only a wreck of my ship was to be seen at low water.", bn: "নিচু জলে শুধু আমার জাহাজের ধ্বংসাবশেষ দেখা যাচ্ছিল।" },
      { en: "I swam to the wreck to rescue and secure for my survival some food and other provisions.", bn: "আমি বেঁচে থাকার জন্য কিছু খাবার ও অন্যান্য জিনিস উদ্ধার করতে ধ্বংসাবশেষে সাঁতার কেটে গেলাম।" },
      { en: "I was able to collect some wood, cable, string, a knife, nails and a gun.", bn: "আমি কিছু কাঠ, তার, দড়ি, ছুরি, পেরেক ও একটি বন্দুক সংগ্রহ করতে পেরেছিলাম।" },
      { en: "I also collected a hammock and some canvas with which I made a tent.", bn: "আমি একটি হ্যামক ও কিছু ক্যানভাসও সংগ্রহ করলাম যাতে তাঁবু তৈরি করলাম।" },
      { en: "I got some ink and paper.", bn: "আমি কিছু কালি ও কাগজ পেয়েছিলাম।" },
      { en: "I also found some money, but they were useless to me in this barren island.", bn: "আমি কিছু টাকাও পেয়েছিলাম, কিন্তু এই অনুর্বর দ্বীপে সেগুলো আমার কোনো কাজে লাগেনি।" },
      { en: "I was some hundred leagues out of the ordinary course of the trade of mankind.", bn: "আমি মানুষের সাধারণ বাণিজ্য পথ থেকে কয়েকশো লীগ দূরে ছিলাম।" },
      { en: "I was convinced I had to spend the rest of my life alone in this wild, desolate island.", bn: "আমি নিশ্চিত হয়েছিলাম যে আমাকে এই বন্য নির্জন দ্বীপে একা জীবনের বাকিটা কাটাতে হবে।" },
      { en: "I searched long for a place of safe habitation.", bn: "আমি নিরাপদ বাসস্থানের জন্য অনেক খুঁজলাম।" },
      { en: "I found a little plain on the side of a rising hill.", bn: "আমি একটি উঁচু পাহাড়ের পাশে একটু সমতল জায়গা পেলাম।" },
      { en: "On the rocky wall of the hill there was a hollow place worn in, like the entrance to a cave.", bn: "পাহাড়ের পাথুরে দেয়ালে একটি ফাঁপা জায়গা ছিল, যেন গুহার প্রবেশপথ।" },
      { en: "On the flat of the green, just before this hollow, I resolved to pitch my tent.", bn: "এই ফাঁপা জায়গার ঠিক সামনের সবুজ সমতল ভূমিতে আমি তাঁবু খাটানোর সিদ্ধান্ত নিলাম।" },
      { en: "I cut the wood I collected, into stakes.", bn: "আমি সংগ্রহ করা কাঠ কেটে খুঁটি তৈরি করলাম।" },
      { en: "I drove them into the ground in a semi-circle around my tent.", bn: "আমি সেগুলো তাঁবুর চারপাশে অর্ধবৃত্তাকারে মাটিতে পুঁতে দিলাম।" },
      { en: "The stakes stood six inches apart from each other.", bn: "খুঁটিগুলো একে অপর থেকে ছয় ইঞ্চি দূরে ছিল।" },
      { en: "I put the cables I had rescued from the ship around the stakes in the manner of a fence.", bn: "জাহাজ থেকে উদ্ধার করা তারগুলো খুঁটির চারপাশে বেড়ার মতো লাগালাম।" },
      { en: "I used a short ladder to go over the fence.", bn: "বেড়া পেরোতে আমি একটি ছোট সিঁড়ি ব্যবহার করতাম।" },
      { en: "Once in, I withdrew the ladder after me so that I was completely fortified against the world outside.", bn: "ভিতরে ঢুকে আমি সিঁড়ি সরিয়ে নিলাম যাতে বাইরের জগতের বিরুদ্ধে সম্পূর্ণ সুরক্ষিত থাকি।" },
      { en: "Into this tent I brought all my stores and provisions.", bn: "এই তাঁবুতে আমি আমার সব মালপত্র ও খাবার এনে রাখলাম।" },
      { en: "After I had been on the island for ten or twelve days, it occurred to me that I would lose the measure of time.", bn: "দ্বীপে দশ-বারো দিন থাকার পর আমার মনে হল যে সময়ের হিসাব হারিয়ে ফেলব।" },
      { en: "This was because I had neither watch nor calendar.", bn: "কারণ আমার না ছিল ঘড়ি, না ছিল ক্যালেন্ডার।" },
      { en: "To prevent this, I cut with my knife upon a large post the date of my landing; I put a notch with my knife for every day.", bn: "এটা রোধ করতে আমি একটি বড় খুঁটিতে ছুরি দিয়ে অবতরণের তারিখ কেটে রাখলাম এবং প্রতিদিন একটি দাগ দিলাম।" },
      { en: "After a long spell of rain, I saw some fair weather around 7th November.", bn: "দীর্ঘ বৃষ্টির পর ৭ নভেম্বরের দিকে কিছুটা ভালো আবহাওয়া দেখলাম।" },
      { en: "I spent the next couple of days making small wood boxes to keep my provisions dry from the rain.", bn: "পরের কয়েকদিন আমি বৃষ্টি থেকে খাবার শুকনো রাখতে ছোট কাঠের বাক্স তৈরি করে কাটালাম।" },
      { en: "Among the things I rescued from the ship there was a small bag of corns meant for poultry feed.", bn: "জাহাজ থেকে উদ্ধার করা জিনিসের মধ্যে হাঁস-মুরগির খাবারের জন্য একটি ছোট ভুট্টার থলে ছিল।" },
      { en: "Most of it had been devoured by rats.", bn: "বেশিরভাগই ইঁদুরে খেয়ে ফেলেছিল।" },
      { en: "I saw nothing but husks and dusts in the bag.", bn: "থলেতে শুধু তুষ ও ধুলো দেখতে পেয়েছিলাম।" },
      { en: "I emptied the contents outside my wall.", bn: "আমি থলের ভিতরের জিনিস দেয়ালের বাইরে ফেলে দিলাম।" },
      { en: "This was a little time before the great rains.", bn: "এটা বড় বৃষ্টির একটু আগের কথা।" },
      { en: "A month later I discovered green stalks shooting out of the ground.", bn: "এক মাস পরে আমি দেখলাম মাটি থেকে সবুজ চারা গজিয়েছে।" },
      { en: "I was astonished to discover it was perfect green barley.", bn: "আমি অবাক হয়ে দেখলাম সেগুলো পুরোপুরি সবুজ যব।" },
      { en: "By the June of 1660, I had gained security of food and shelter.", bn: "১৬৬০ সালের জুন মাসের মধ্যে আমি খাবার ও আশ্রয়ের নিরাপত্তা পেয়ে গিয়েছিলাম।" },
      { en: "In this same month I developed a high fever and lay weak and thirsty.", bn: "একই মাসে আমার তীব্র জ্বর হয় এবং আমি দুর্বল ও তৃষ্ণার্ত হয়ে পড়ে থাকি।" },
      { en: "I recovered around 30th and gradually felt stronger than the day before.", bn: "৩০ তারিখের দিকে সুস্থ হয়ে উঠি এবং ধীরে ধীরে আগের দিনের চেয়ে শক্তিশালী বোধ করি।" },
      { en: "On 15th of July I took a more particular survey of the island.", bn: "১৫ জুলাই আমি দ্বীপের আরও বিস্তারিত জরিপ করলাম।" },
      { en: "Around two miles up, I found a brook with pleasant meadows by its bank, plain, smooth and covered by grass.", bn: "প্রায় দুই মাইল উপরে একটি নদী পেলাম, যার তীরে সুন্দর তৃণভূমি, সমতল, মসৃণ ও ঘাসে ঢাকা।" },
      { en: "In a woody part I found melons in great abundance, and grape trees.", bn: "একটি জঙ্গল অংশে প্রচুর তরমুজ ও আঙুর গাছ পেয়েছিলাম।" },
      { en: "The grapes were ripe and rich.", bn: "আঙুরগুলো পাকা ও রসালো ছিল।" },
      { en: "Further into the land I found a great number of cocoa, orange and lemon trees.", bn: "আরও ভিতরে গিয়ে প্রচুর কোকো, কমলা ও লেবুর গাছ পেয়েছিলাম।" },
      { en: "I carried great parcels of fruit homeward and the journey took me three days.", bn: "আমি প্রচুর ফল নিয়ে বাড়ি ফিরছিলাম এবং যাত্রা তিন দিন লেগেছিল।" },
      { en: "I was tempted to transfer my habitation to this valley of fruits.", bn: "আমি এই ফলের উপত্যকায় বাসস্থান স্থানান্তর করতে লোভ অনুভব করেছিলাম।" },
      { en: "I did not, because I still hoped to be rescued by some passing ship on the sea.", bn: "কিন্তু করিনি, কারণ এখনও সমুদ্রপথে কোনো জাহাজের উদ্ধারের আশা ছিল।" },
      { en: "I did not want to enclose myself in hill and woods.", bn: "আমি নিজেকে পাহাড় ও জঙ্গলে আবদ্ধ করতে চাইনি।" },
      { en: "I stayed in view of the sea.", bn: "আমি সমুদ্রের দৃষ্টিসীমায় থেকেছিলাম।" },
      { en: "Ten months had passed since I had set foot on this island.", bn: "এই দ্বীপে পা রাখার পর দশ মাস কেটে গিয়েছিল।" },
      { en: "Previously I had no lamp after dark.", bn: "আগে অন্ধকার হলে আমার কোনো প্রদীপ ছিল না।" },
      { en: "I collected a little tallow and a small clay dish.", bn: "আমি কিছু পশুর চর্বি ও একটি ছোট মাটির থালা সংগ্রহ করলাম।" },
      { en: "To this I added a wick.", bn: "এতে একটি সলতে যোগ করলাম।" },
      { en: "I had thus made myself a lamp.", bn: "এভাবে আমি নিজের জন্য একটি প্রদীপ তৈরি করলাম।" },
      { en: "I now began to seriously consider the circumstance I was reduced to.", bn: "এখন আমি যে অবস্থায় পড়েছি তা গুরুত্ব সহকারে বিবেচনা করতে শুরু করলাম।" },
      { en: "I decided to describe my state of affairs in writing.", bn: "আমি আমার অবস্থা লিখে রাখার সিদ্ধান্ত নিলাম।" },
      { en: "I began to keep a journal of every day’s employment.", bn: "আমি প্রতিদিনের কাজের একটি ডায়েরি রাখা শুরু করলাম।" },
      { en: "I could not include all particulars because gradually I ran out of ink.", bn: "সব বিবরণ রাখতে পারিনি কারণ ধীরে ধীরে কালি ফুরিয়ে গিয়েছিল।" },
      { en: "I found, by the notches I cast on the post, it was September 30th again.", bn: "খুঁটিতে দেওয়া দাগ দেখে বুঝলাম আবার ৩০ সেপ্টেম্বর এসেছে।" },
      { en: "I had spent three hundred and sixty five days on this island.", bn: "আমি এই দ্বীপে তিনশো পঁয়ষট্টি দিন কাটিয়েছি।" }
    ],
    words: {
      dismal: { en: "desolate", bn: "বিষণ্ণ / নির্জন" },
      devoured: { en: "ate all of something quickly", bn: "দ্রুত খেয়ে ফেলা" },
      hammock: { en: "a kind of hanging bed generally made of net", bn: "ঝুলন্ত বিছানা" },
      fortified: { en: "secured", bn: "সুরক্ষিত করা" },
      notch: { en: "mark", bn: "দাগ" },
      tallow: { en: "animal fat used to make candles", bn: "মোমবাতির জন্য পশুর চর্বি" }
    }
  },

  "hunting-snake": {
    title: "Hunting Snake",
    author: "Judith Wright",
    initials: "JW",
    bio: "Judith Arundell Wright (1915–2000) was an Australian poet and environmentalist. Among several collections of her poetry, the most notable are The Moving Image, Woman to Man, The Gateway and many more.",
    critical: "The poem captures a sudden encounter with a black snake. Wright presents the snake as both beautiful and dangerous (‘cold, dark and splendid’). The observers freeze in awe. The poem explores the tension between human life and the wild power of nature, ending with a deeper awareness of the day.",
    sentences: [
      { en: "Sun-warmed in the late season’s grace", bn: "দেরি ঋতুর অনুগ্রহে সূর্য-উষ্ণ", type: "poem" },
      { en: "Under the autumn’s gentlest sky", bn: "শরতের সবচেয়ে মৃদু আকাশের নিচে", type: "poem" },
      { en: "We walked and froze half-through a pace.", bn: "আমরা হাঁটছিলাম এবং মাঝপথে থমকে গেলাম।", type: "poem" },
      { en: "The great black snake went reeling by.", bn: "বিশাল কালো সাপটি ঘুরতে ঘুরতে চলে গেল।", type: "poem" },
      { en: "Head down, tongue flickering on the trail", bn: "মাথা নিচু করে, জিভ ঝিলিক দিয়ে পথে", type: "poem" },
      { en: "He quested through the parting grass.", bn: "সে ফাঁক করা ঘাসের মধ্যে শিকার খুঁজছিল।", type: "poem" },
      { en: "Sun glazed his curves of diamond scale", bn: "সূর্য তার হীরক আঁশের বাঁকগুলিকে চকচকে করে তুলেছিল", type: "poem" },
      { en: "And we lost breath to see him pass.", bn: "এবং তাকে যেতে দেখে আমাদের শ্বাস বন্ধ হয়ে গিয়েছিল।", type: "poem" },
      { en: "What track he followed, what small food", bn: "সে কোন পথ অনুসরণ করছিল, কোন ছোট শিকার", type: "poem" },
      { en: "Fled living from his fierce intent,", bn: "তার তীব্র অভিপ্রায় থেকে পালিয়ে যাচ্ছিল,", type: "poem" },
      { en: "We scarcely thought; still as we stood", bn: "আমরা খুব কমই ভেবেছিলাম; আমরা যেমন দাঁড়িয়ে ছিলাম", type: "poem" },
      { en: "Our eyes went with him as he went.", bn: "আমাদের চোখ তার সঙ্গে চলেছিল।", type: "poem" },
      { en: "Cold, dark and splendid he was gone", bn: "ঠান্ডা, অন্ধকার ও জমকালো হয়ে সে চলে গেল", type: "poem" },
      { en: "Into the grass that hid his prey.", bn: "ঘাসের মধ্যে যা তার শিকারকে লুকিয়ে রেখেছিল।", type: "poem" },
      { en: "We took a deeper breath of day,", bn: "আমরা দিনের আরও গভীর শ্বাস নিলাম,", type: "poem" },
      { en: "Looked at each other, and went on.", bn: "একে অপরের দিকে তাকালাম, এবং এগিয়ে চললাম।", type: "poem" }
    ],
    words: {
      reeling: { en: "moving unsteadily or with a swirling motion", bn: "ঘুরতে ঘুরতে চলা" },
      quested: { en: "searched; hunted", bn: "অনুসন্ধান / শিকার করা" },
      glazed: { en: "covered with a shiny surface", bn: "চকচকে করা" },
      fierce: { en: "intense; aggressive", bn: "তীব্র" },
      splendid: { en: "magnificent; impressive", bn: "জমকালো" }
    }
  }
};
